import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/* fluxiaRSS Obsidian plugin - generated by esbuild */`;

const ctx = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: ["obsidian", "electron", "@codemirror/autocomplete", "@codemirror/collab", "@codemirror/commands", "@codemirror/language", "@codemirror/lint", "@codemirror/search", "@codemirror/state", "@codemirror/view", "@lezer/common", "@lezer/highlight", "@lezer/lr", ...builtins],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: process.argv[2] === "production" ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (process.argv[2] === "production") {
  await ctx.rebuild();
  process.exit(0);
} else {
  await ctx.watch();
}
