/* fluxiaRSS Obsidian plugin - generated by esbuild */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FluxiaRSSPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  apiBase: "http://localhost:8000",
  apiToken: "",
  digestDir: "FluxiaRSS",
  digestSize: 8,
  autoRefreshHour: 6
};
var RATED_ACTIONS = [
  { score: null, action: "later", label: "\u{1F552} \u7A0D\u540E\u8BFB" },
  { score: null, action: "skip", label: "\u23ED \u8DF3\u8FC7" }
];
function fetchWithTimeout(opts, timeoutMs) {
  const main = (0, import_obsidian.requestUrl)(opts);
  main.catch(() => {
  });
  let timer;
  const to = new Promise((_, reject) => {
    timer = window.setTimeout(
      () => reject(new Error(`\u8BF7\u6C42\u8D85\u65F6\uFF08${timeoutMs / 1e3}s\uFF09`)),
      timeoutMs
    );
  });
  return Promise.race([main, to]).finally(() => window.clearTimeout(timer));
}
function todayStr() {
  const d = /* @__PURE__ */ new Date();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${d.getFullYear()}-${m}-${day}`;
}
function ratedText(r) {
  if (r.action === "later") return "\u2713 \u5DF2\u8BC4\uFF08\u7A0D\u540E\u8BFB\uFF09";
  if (r.action === "skip") return "\u2713 \u5DF2\u8BC4\uFF08\u8DF3\u8FC7\uFF09";
  return `\u2713 \u5DF2\u8BC4 ${r.score}/10`;
}
var FluxiaRSSPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.ratings = {};
  }
  async onload() {
    await this.loadSettings();
    this.registerMarkdownCodeBlockProcessor(
      "fluxiars",
      (source, el, ctx) => {
        let digest;
        try {
          digest = JSON.parse(source);
        } catch (e) {
          el.createEl("p", { text: "\u274C digest \u6570\u636E\u89E3\u6790\u5931\u8D25\uFF0C\u8BF7\u7528\u300C\u5237\u65B0\u4ECA\u65E5\u667A\u8BFB\u300D\u91CD\u8BD5\u3002" });
          return;
        }
        new DigestRenderer(this, digest, ctx.sourcePath).renderInto(el);
      }
    );
    this.addCommand({
      id: "open-today-digest",
      name: "\u6253\u5F00\u4ECA\u65E5\u667A\u8BFB",
      callback: () => this.openToday(false)
    });
    this.addCommand({
      id: "refresh-today-digest",
      name: "\u5237\u65B0\u4ECA\u65E5\u667A\u8BFB",
      callback: () => this.openToday(true)
    });
    this.addCommand({
      id: "collect-and-refresh",
      name: "\u7ACB\u5373\u91C7\u96C6\u5E76\u5237\u65B0\u4ECA\u65E5\u667A\u8BFB",
      callback: () => this.collectAndRefresh()
    });
    this.addSettingTab(new FluxiaSettingTab(this.app, this));
    this.registerInterval(
      window.setInterval(() => this.maybeAutoRefresh(), 60 * 60 * 1e3)
    );
    if (!await this.todayExists()) {
      await this.generateTodayNote().catch(
        (e) => new import_obsidian.Notice(`\u{1F4F0} fluxiaRSS \u751F\u6210\u4ECA\u65E5\u667A\u8BFB\u5931\u8D25\uFF1A${e.message}`)
      );
    }
  }
  // ---- 设置 ----
  async loadSettings() {
    var _a, _b;
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, (_a = data == null ? void 0 : data.settings) != null ? _a : {});
    this.ratings = (_b = data == null ? void 0 : data.ratings) != null ? _b : {};
  }
  async saveAll() {
    await this.saveData({ settings: this.settings, ratings: this.ratings });
  }
  /** 带鉴权头的 API 调用：拼 base、附 X-Fluxia-Token（未配置 token 则不附带）。 */
  async api(urlPath, opts = {}) {
    var _a, _b;
    return fetchWithTimeout(
      {
        url: `${this.settings.apiBase}${urlPath}`,
        method: (_a = opts.method) != null ? _a : "GET",
        contentType: "application/json",
        headers: this.settings.apiToken ? { "X-Fluxia-Token": this.settings.apiToken } : void 0,
        body: opts.body !== void 0 ? JSON.stringify(opts.body) : void 0
      },
      (_b = opts.timeout) != null ? _b : 1e4
    );
  }
  // ---- 拉取与笔记 ----
  getTodayPath() {
    return `${this.settings.digestDir}/${todayStr()}.md`;
  }
  async todayExists() {
    return this.app.vault.adapter.exists(this.getTodayPath());
  }
  async fetchDigest() {
    const res = await this.api(`/api/v1/digest?top=${this.settings.digestSize}`);
    if (res.status !== 200) throw new Error(`HTTP ${res.status}`);
    return res.json;
  }
  /**
   * 生成今日笔记。force=true 时覆盖重写（刷新）；否则已存在则跳过。
   * 返回文件（可能为 null：已存在且未强制刷新）。
   */
  async generateTodayNote(force = false) {
    const path = this.getTodayPath();
    if (!force && await this.app.vault.adapter.exists(path)) return null;
    const digest = await this.fetchDigest();
    digest.generated = (/* @__PURE__ */ new Date()).toISOString();
    const content = [
      "---",
      `date: ${digest.date}`,
      `generated: ${digest.generated}`,
      "---",
      "",
      `# \u{1F4F0} \u4ECA\u65E5\u667A\u8BFB \xB7 ${digest.date}`,
      "",
      `> \u751F\u6210\u4E8E ${new Date(digest.generated).toTimeString().slice(0, 5)} \xB7 \u5BF9\u6587\u7AE0\u6253\u5206/\u8DF3\u8FC7\uFF0C\u53CD\u9988\u8FDB\u5165\u957F\u671F\u8BB0\u5FC6\uFF0C\u5F71\u54CD\u660E\u5929\u6392\u5E8F\u3002`,
      "",
      "```fluxiars",
      JSON.stringify(digest),
      "```",
      ""
    ].join("\n");
    await this.app.vault.createFolder(this.settings.digestDir).catch(() => {
    });
    await this.app.vault.adapter.write(path, content);
    const f = this.app.vault.getAbstractFileByPath(path);
    return f instanceof import_obsidian.TFile ? f : null;
  }
  async openToday(refresh) {
    try {
      const file = await this.generateTodayNote(refresh);
      const target = file != null ? file : this.app.vault.getAbstractFileByPath(this.getTodayPath());
      if (target instanceof import_obsidian.TFile) {
        const leaf = this.app.workspace.getLeaf(false);
        await leaf.openFile(target);
      } else {
        new import_obsidian.Notice("\u4ECA\u65E5\u667A\u8BFB\u7B14\u8BB0\u4E0D\u5B58\u5728\uFF0C\u62C9\u53D6\u5931\u8D25");
      }
    } catch (e) {
      new import_obsidian.Notice(`\u{1F4F0} fluxiaRSS \u62C9\u53D6\u5931\u8D25\uFF1A${e.message}`);
    }
  }
  async maybeAutoRefresh() {
    const hour = (/* @__PURE__ */ new Date()).getHours();
    if (hour < this.settings.autoRefreshHour) return;
    if (await this.todayExists()) return;
    try {
      const file = await this.generateTodayNote();
      if (file) new import_obsidian.Notice("\u{1F4F0} \u4ECA\u65E5\u667A\u8BFB\u5DF2\u81EA\u52A8\u751F\u6210");
    } catch (e) {
      new import_obsidian.Notice(`\u{1F4F0} fluxiaRSS \u81EA\u52A8\u751F\u6210\u5931\u8D25\uFF1A${e.message}`);
    }
  }
  async collectAndRefresh() {
    var _a, _b;
    try {
      const res = await this.api("/api/v1/collect", {
        method: "POST",
        body: {},
        timeout: 12e4
      });
      const body = res.json;
      new import_obsidian.Notice(`\u91C7\u96C6\u5B8C\u6210\uFF1A\u62C9\u53D6 ${(_a = body == null ? void 0 : body.fetched) != null ? _a : "?"}\uFF0C\u65B0\u589E ${(_b = body == null ? void 0 : body.new_added) != null ? _b : "?"}`);
    } catch (e) {
      new import_obsidian.Notice(`\u91C7\u96C6\u5931\u8D25\uFF1A${e.message}`);
    }
    await this.openToday(true);
  }
  // ---- 评分 ----
  async submitRating(articleId, score, action) {
    const res = await this.api("/api/v1/rating", {
      method: "POST",
      body: { article_id: articleId, score, action }
    });
    if (res.status !== 200 && res.status !== 201) {
      throw new Error(`HTTP ${res.status}`);
    }
    this.ratings[articleId] = { score, action };
    await this.saveAll();
  }
  /** 给已评分文章补写评论（action=comment，服务端更新最近一条评分行的 comment）。 */
  async submitComment(articleId, comment) {
    var _a;
    const res = await this.api("/api/v1/rating", {
      method: "POST",
      body: { article_id: articleId, comment, action: "comment" }
    });
    if (res.status !== 200 && res.status !== 201) {
      throw new Error(`HTTP ${res.status}`);
    }
    const prev = (_a = this.ratings[articleId]) != null ? _a : { score: null, action: "read" };
    this.ratings[articleId] = { ...prev, comment };
    await this.saveAll();
  }
};
var DigestRenderer = class {
  constructor(plugin, digest, sourcePath) {
    this.plugin = plugin;
    this.digest = digest;
    this.sourcePath = sourcePath;
    this.rootEl = null;
  }
  renderInto(el) {
    el.addClass("fluxiars-digest");
    el.empty();
    this.rootEl = el;
    if (!this.digest.items || this.digest.items.length === 0) {
      el.createEl("p", {
        text: "\u4ECA\u65E5\u6682\u65E0\u5185\u5BB9\uFF08\u670D\u52A1\u7AEF\u51CC\u6668\u91C7\u96C6\u540E\u5237\u65B0\u5373\u53EF\uFF09\u3002"
      });
      return;
    }
    this.mergeServerRatings();
    const header = el.createDiv({ cls: "fluxiars-header" });
    const gen = this.digest.generated ? new Date(this.digest.generated).toTimeString().slice(0, 5) : "\u2014";
    header.createEl("span", {
      text: `\u{1F4F0} ${this.digest.date} \xB7 ${this.digest.items.length} \u7BC7 \xB7 \u751F\u6210 ${gen}`
    });
    const refreshBtn = header.createEl("button", {
      cls: "fluxiars-refresh",
      text: "\u{1F504} \u5237\u65B0"
    });
    refreshBtn.addEventListener("click", () => void this.onRefresh(refreshBtn));
    for (const item of this.digest.items) {
      this.renderItem(el, item);
    }
  }
  /**
   * 手动刷新：从服务端重拉 digest（rank/reason/rated/comment 全量刷新），
   * 就地重渲染，并把最新 JSON 写回当前笔记的 fluxiars 代码块（只替换该块）。
   */
  async onRefresh(btn) {
    btn.disabled = true;
    btn.setText("\u5237\u65B0\u4E2D\u2026");
    try {
      const fresh = await this.plugin.fetchDigest();
      fresh.generated = (/* @__PURE__ */ new Date()).toISOString();
      this.digest = fresh;
      if (this.rootEl) this.renderInto(this.rootEl);
      await this.persistToNote();
      new import_obsidian.Notice("\u5DF2\u5237\u65B0\u72B6\u6001 \u2714");
    } catch (e) {
      new import_obsidian.Notice(`\u5237\u65B0\u5931\u8D25\uFF1A${e.message}`);
    } finally {
      btn.disabled = false;
      btn.setText("\u{1F504} \u5237\u65B0");
    }
  }
  /** 把当前 digest JSON 写回笔记的 fluxiars 代码块；不触碰其他内容。 */
  async persistToNote() {
    try {
      const file = this.plugin.app.vault.getAbstractFileByPath(this.sourcePath);
      if (!(file instanceof import_obsidian.TFile)) return;
      const json = JSON.stringify(this.digest);
      await this.plugin.app.vault.process(file, (raw) => {
        const updated = raw.replace(
          /```fluxiars\n[\s\S]*?\n```/,
          () => `\`\`\`fluxiars
${json}
\`\`\``
        );
        return updated === raw ? raw : updated;
      });
    } catch (e) {
      new import_obsidian.Notice(`\u72B6\u6001\u843D\u76D8\u5931\u8D25\uFF08\u4E0D\u5F71\u54CD\u663E\u793A\uFF09\uFF1A${e.message}`);
    }
  }
  /**
   * 把服务端返回的最近一次评分合并进本地 ratings：本库已评过则以本地为准
   * （更新鲜），未评过的标记为「已评」，实现跨库/跨端状态同步。
   */
  mergeServerRatings() {
    var _a, _b;
    for (const item of this.digest.items) {
      const rated = item.rated;
      if (!rated) continue;
      if (this.plugin.ratings[item.article_id]) continue;
      this.plugin.ratings[item.article_id] = {
        score: (_a = rated.score) != null ? _a : null,
        action: rated.action,
        comment: (_b = rated.comment) != null ? _b : void 0
      };
    }
    void this.plugin.saveAll();
  }
  renderItem(el, item) {
    const card = el.createDiv({ cls: "fluxiars-card" });
    const top = card.createDiv({ cls: "fluxiars-card-top" });
    top.createEl("span", { cls: "fluxiars-rank", text: `${item.rank}` });
    top.createEl("a", { cls: "fluxiars-title", text: item.title, href: item.url }).addEventListener("click", (ev) => {
      ev.preventDefault();
      window.open(item.url, "_blank");
    });
    if (item.source) {
      card.createEl("div", { cls: "fluxiars-source", text: `\u6765\u6E90\uFF1A${item.source}` });
    }
    if (item.reason) {
      card.createEl("div", { cls: "fluxiars-reason", text: `\u6392\u5E8F\uFF1A${item.reason}` });
    }
    if (item.summary) {
      card.createEl("div", { cls: "fluxiars-summary", text: item.summary });
    }
    const row = card.createDiv({ cls: "fluxiars-actions" });
    this.renderActions(row, card, item);
  }
  renderActions(row, card, item) {
    const rated = this.plugin.ratings[item.article_id];
    if (rated) {
      const r = { score: rated.score, action: rated.action, label: "" };
      row.createEl("span", { cls: "fluxiars-rated", text: ratedText(r) });
      this.renderCommentArea(card, item, rated);
      return;
    }
    const scoreInput = row.createEl("input", {
      cls: "fluxiars-score-input",
      type: "number",
      placeholder: "0-10",
      attr: { min: "0", max: "10", step: "1" }
    });
    const scoreBtn = row.createEl("button", { cls: "fluxiars-btn", text: "\u2713 \u6253\u5206" });
    const doScore = () => {
      const raw = scoreInput.value.trim();
      const v = Number(raw);
      if (raw === "" || !Number.isInteger(v) || v < 0 || v > 10) {
        new import_obsidian.Notice("\u8BF7\u8F93\u5165 0-10 \u7684\u6574\u6570\u5206\u6570");
        return;
      }
      void this.complete(scoreBtn, item, row, card, v, "read", "\u2713 \u6253\u5206");
    };
    scoreInput.addEventListener("keydown", (ev) => {
      if (ev.key === "Enter") doScore();
    });
    scoreBtn.addEventListener("click", doScore);
    for (const ra of RATED_ACTIONS) {
      const btn = row.createEl("button", { cls: "fluxiars-btn", text: ra.label });
      btn.addEventListener(
        "click",
        () => void this.complete(btn, item, row, card, null, ra.action, ra.label)
      );
    }
  }
  /** 提交评分/动作并刷新卡片状态；失败则恢复按钮，不静默。 */
  async complete(btn, item, row, card, score, action, label) {
    btn.disabled = true;
    btn.setText("\u2026");
    try {
      await this.plugin.submitRating(item.article_id, score, action);
      row.empty();
      const ra = { score, action, label: "" };
      row.createEl("span", { cls: "fluxiars-rated", text: ratedText(ra) });
      this.renderCommentArea(card, item, this.plugin.ratings[item.article_id]);
      new import_obsidian.Notice("\u5DF2\u8BB0\u5F55\u53CD\u9988 \u2714");
    } catch (e) {
      btn.disabled = false;
      btn.setText(label);
      new import_obsidian.Notice(`\u8BC4\u5206\u5931\u8D25\uFF1A${e.message}`);
    }
  }
  /** 卡片评论区：已有评论则显示，否则放一个可选的评论输入框（Enter 提交）。 */
  renderCommentArea(card, item, rated) {
    var _a;
    (_a = card.querySelector(".fluxiars-comment")) == null ? void 0 : _a.remove();
    if (!rated) return;
    const area = card.createDiv({ cls: "fluxiars-comment" });
    if (rated.comment) {
      area.createEl("span", { cls: "fluxiars-comment-text", text: `\u{1F4AC} ${rated.comment}` });
      return;
    }
    const input = area.createEl("input", {
      cls: "fluxiars-comment-input",
      type: "text",
      placeholder: "\u270D\uFE0F \u60F3\u8BB0\u4E00\u53E5\uFF1F\uFF08Enter \u63D0\u4EA4\uFF0C\u53EF\u8DF3\u8FC7\uFF09"
    });
    input.addEventListener("keydown", async (ev) => {
      if (ev.key !== "Enter") return;
      const text = input.value.trim();
      if (!text) return;
      input.disabled = true;
      try {
        await this.plugin.submitComment(item.article_id, text);
        area.empty();
        area.createEl("span", { cls: "fluxiars-comment-text", text: `\u{1F4AC} ${text}` });
        new import_obsidian.Notice("\u8BC4\u8BBA\u5DF2\u8BB0\u5F55 \u2714");
      } catch (e) {
        input.disabled = false;
        new import_obsidian.Notice(`\u8BC4\u8BBA\u5931\u8D25\uFF1A${e.message}`);
      }
    });
  }
};
var FluxiaSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "fluxiaRSS \u4ECA\u65E5\u667A\u8BFB" });
    new import_obsidian.Setting(containerEl).setName("API \u5730\u5740").setDesc("fluxiaRSS \u670D\u52A1\u7AEF\u5730\u5740\uFF0C\u5982 http://192.168.1.5:8000").addText(
      (t) => t.setValue(this.plugin.settings.apiBase).onChange(async (v) => {
        this.plugin.settings.apiBase = v.trim() || DEFAULT_SETTINGS.apiBase;
        await this.plugin.saveAll();
      })
    );
    new import_obsidian.Setting(containerEl).setName("API \u4EE4\u724C").setDesc("\u670D\u52A1\u7AEF .env \u91CC\u7684 FLUXIARSS_API_TOKEN\uFF08\u7559\u7A7A\u5219\u4E0D\u505A\u9274\u6743\uFF0C\u4EC5\u9650\u672C\u673A\u8C03\u8BD5\uFF09").addText((t) => {
      t.setValue(this.plugin.settings.apiToken).onChange(async (v) => {
        this.plugin.settings.apiToken = v.trim();
        await this.plugin.saveAll();
      });
      t.inputEl.type = "password";
      t.inputEl.placeholder = "FLUXIARSS_API_TOKEN \u7684\u503C";
    });
    new import_obsidian.Setting(containerEl).setName("digest \u76EE\u5F55").setDesc("\u6BCF\u65E5\u7B14\u8BB0\u5B58\u653E\u76EE\u5F55\uFF08vault \u5185\u76F8\u5BF9\u8DEF\u5F84\uFF09").addText(
      (t) => t.setValue(this.plugin.settings.digestDir).onChange(async (v) => {
        this.plugin.settings.digestDir = v.trim() || DEFAULT_SETTINGS.digestDir;
        await this.plugin.saveAll();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6BCF\u65E5\u7BC7\u6570\uFF08Top-K\uFF09").setDesc("\u6BCF\u65E5\u667A\u8BFB\u7CBE\u9009\u7684\u6761\u6570\uFF08\u62C9\u53D6 digest \u65F6\u4F20\u7ED9\u670D\u52A1\u7AEF ?top=\uFF09").addSlider(
      (s) => s.setLimits(1, 30, 1).setValue(this.plugin.settings.digestSize).setDynamicTooltip().onChange(async (v) => {
        this.plugin.settings.digestSize = v;
        await this.plugin.saveAll();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u81EA\u52A8\u751F\u6210\u65F6\u95F4").setDesc("\u8FC7\u4E86\u8BE5\u5C0F\u65F6\u4E14\u4ECA\u65E5\u7B14\u8BB0\u4E0D\u5B58\u5728\u65F6\u81EA\u52A8\u751F\u6210\uFF080-23\uFF09").addSlider(
      (s) => s.setLimits(0, 23, 1).setValue(this.plugin.settings.autoRefreshHour).setDynamicTooltip().onChange(async (v) => {
        this.plugin.settings.autoRefreshHour = v;
        await this.plugin.saveAll();
      })
    );
    this.renderSourcesSection(containerEl);
  }
  // ---- RSS 源管理（服务端 DB 持久化） ----
  renderSourcesSection(containerEl) {
    containerEl.createEl("h3", { text: "RSS \u6E90" });
    containerEl.createEl("p", {
      cls: "setting-item-description",
      text: "\u589E\u5220\u81EA\u5B9A\u4E49 RSS \u6E90\uFF08\u5185\u7F6E\u6E90\u4E5F\u5217\u4E8E\u6B64\uFF09\u3002\u6539\u52A8\u540E\u8FD0\u884C\u300C\u7ACB\u5373\u91C7\u96C6\u5E76\u5237\u65B0\u300D\u62C9\u53D6\u65B0\u6E90\u3002"
    });
    const bar = containerEl.createDiv({ cls: "fluxiars-source-bar" });
    bar.createEl("button", { text: "\u{1F504} \u5237\u65B0\u5217\u8868", cls: "fluxiars-source-refresh" }).addEventListener("click", () => this.refreshSources(listEl));
    const listEl = containerEl.createDiv({ cls: "fluxiars-source-list" });
    listEl.createEl("p", { cls: "fluxiars-source-muted", text: "\u52A0\u8F7D\u4E2D\u2026" });
    const nameInput = containerEl.createEl("input", {
      type: "text",
      placeholder: "\u540D\u79F0\uFF08\u53EF\u9009\uFF0C\u9ED8\u8BA4\u7528\u57DF\u540D\uFF09",
      cls: "fluxiars-source-input"
    });
    const urlInput = containerEl.createEl("input", {
      type: "text",
      placeholder: "RSS URL\uFF08\u5FC5\u586B\uFF0C\u5982 https://example.com/feed.xml\uFF09",
      cls: "fluxiars-source-input"
    });
    const addBtn = containerEl.createEl("button", {
      text: "\uFF0B \u6DFB\u52A0\u6E90",
      cls: "fluxiars-source-addbtn"
    });
    urlInput.addEventListener("keydown", (ev) => {
      if (ev.key === "Enter") addBtn.click();
    });
    addBtn.addEventListener("click", async () => {
      const url = urlInput.value.trim();
      if (!url) {
        new import_obsidian.Notice("\u8BF7\u5148\u586B\u5199 RSS URL");
        return;
      }
      addBtn.disabled = true;
      addBtn.setText("\u6DFB\u52A0\u4E2D\u2026");
      try {
        const res = await this.plugin.api("/api/v1/sources", {
          method: "POST",
          body: { url, name: nameInput.value.trim() || void 0 }
        });
        if (res.status !== 200 && res.status !== 201) {
          throw new Error(`HTTP ${res.status}`);
        }
        nameInput.value = "";
        urlInput.value = "";
        await this.refreshSources(listEl);
        new import_obsidian.Notice("\u6E90\u5DF2\u6DFB\u52A0 \u2714");
      } catch (e) {
        new import_obsidian.Notice(`\u6DFB\u52A0\u5931\u8D25\uFF1A${e.message}`);
      } finally {
        addBtn.disabled = false;
        addBtn.setText("\uFF0B \u6DFB\u52A0\u6E90");
      }
    });
    void this.refreshSources(listEl);
  }
  /** 拉取 /api/v1/sources 并渲染列表；失败时在列表位显示错误而非抛错。 */
  async refreshSources(listEl) {
    var _a;
    listEl.empty();
    listEl.createEl("p", { cls: "fluxiars-source-muted", text: "\u52A0\u8F7D\u4E2D\u2026" });
    try {
      const res = await this.plugin.api("/api/v1/sources");
      if (res.status !== 200) throw new Error(`HTTP ${res.status}`);
      const sources = (_a = res.json) != null ? _a : [];
      listEl.empty();
      if (sources.length === 0) {
        listEl.createEl("p", { cls: "fluxiars-source-muted", text: "\uFF08\u6682\u65E0\u6E90\uFF0C\u8BF7\u6DFB\u52A0\uFF09" });
        return;
      }
      for (const s of sources) {
        const row = listEl.createDiv({ cls: "fluxiars-source-row" });
        const info = row.createDiv({ cls: "fluxiars-source-info" });
        info.createEl("span", { cls: "fluxiars-source-name", text: s.name });
        info.createEl("span", { cls: "fluxiars-source-url", text: s.url });
        info.createEl("span", {
          cls: s.custom ? "fluxiars-source-badge fluxiars-source-badge-custom" : "fluxiars-source-badge",
          text: s.custom ? "\u81EA\u5B9A\u4E49" : "\u5185\u7F6E"
        });
        const del = row.createEl("button", { cls: "fluxiars-source-del", text: "\u5220\u9664" });
        del.addEventListener("click", async () => {
          del.disabled = true;
          del.setText("\u2026");
          try {
            const r = await this.plugin.api(
              `/api/v1/sources?url=${encodeURIComponent(s.url)}`,
              { method: "DELETE" }
            );
            if (r.status !== 200) throw new Error(`HTTP ${r.status}`);
            await this.refreshSources(listEl);
            new import_obsidian.Notice("\u6E90\u5DF2\u5220\u9664 \u2714");
          } catch (e) {
            del.disabled = false;
            del.setText("\u5220\u9664");
            new import_obsidian.Notice(`\u5220\u9664\u5931\u8D25\uFF1A${e.message}`);
          }
        });
      }
    } catch (e) {
      listEl.empty();
      listEl.createEl("p", {
        cls: "fluxiars-source-muted",
        text: `\u274C \u83B7\u53D6\u6E90\u5217\u8868\u5931\u8D25\uFF1A${e.message}`
      });
    }
  }
};
