/* fluxiaRSS Obsidian plugin - generated by esbuild */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FluxiaRSSPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  apiBase: "http://localhost:8000",
  digestDir: "FluxiaRSS",
  autoRefreshHour: 6
};
var RATED_ACTIONS = [
  { score: 9, action: "read", label: "\u{1F44D} \u9AD8" },
  { score: 5, action: "read", label: "\u2B50 \u4E2D" },
  { score: 1, action: "read", label: "\u{1F44E} \u4F4E" },
  { score: null, action: "later", label: "\u{1F552} \u7A0D\u540E\u8BFB" },
  { score: null, action: "skip", label: "\u23ED \u8DF3\u8FC7" }
];
function fetchWithTimeout(opts, timeoutMs) {
  const main = (0, import_obsidian.requestUrl)(opts);
  main.catch(() => {
  });
  let timer;
  const to = new Promise((_, reject) => {
    timer = window.setTimeout(
      () => reject(new Error(`\u8BF7\u6C42\u8D85\u65F6\uFF08${timeoutMs / 1e3}s\uFF09`)),
      timeoutMs
    );
  });
  return Promise.race([main, to]).finally(() => window.clearTimeout(timer));
}
function todayStr() {
  const d = /* @__PURE__ */ new Date();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${d.getFullYear()}-${m}-${day}`;
}
function ratedText(r) {
  if (r.action === "later") return "\u2713 \u5DF2\u8BC4\uFF08\u7A0D\u540E\u8BFB\uFF09";
  if (r.action === "skip") return "\u2713 \u5DF2\u8BC4\uFF08\u8DF3\u8FC7\uFF09";
  return `\u2713 \u5DF2\u8BC4 ${r.score}/10`;
}
var FluxiaRSSPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.ratings = {};
  }
  async onload() {
    await this.loadSettings();
    this.registerMarkdownCodeBlockProcessor(
      "fluxiars",
      (source, el) => {
        let digest;
        try {
          digest = JSON.parse(source);
        } catch (e) {
          el.createEl("p", { text: "\u274C digest \u6570\u636E\u89E3\u6790\u5931\u8D25\uFF0C\u8BF7\u7528\u300C\u5237\u65B0\u4ECA\u65E5\u667A\u8BFB\u300D\u91CD\u8BD5\u3002" });
          return;
        }
        new DigestRenderer(this, digest).renderInto(el);
      }
    );
    this.addCommand({
      id: "open-today-digest",
      name: "\u6253\u5F00\u4ECA\u65E5\u667A\u8BFB",
      callback: () => this.openToday(false)
    });
    this.addCommand({
      id: "refresh-today-digest",
      name: "\u5237\u65B0\u4ECA\u65E5\u667A\u8BFB",
      callback: () => this.openToday(true)
    });
    this.addCommand({
      id: "collect-and-refresh",
      name: "\u7ACB\u5373\u91C7\u96C6\u5E76\u5237\u65B0\u4ECA\u65E5\u667A\u8BFB",
      callback: () => this.collectAndRefresh()
    });
    this.addSettingTab(new FluxiaSettingTab(this.app, this));
    this.registerInterval(
      window.setInterval(() => this.maybeAutoRefresh(), 60 * 60 * 1e3)
    );
    if (!await this.todayExists()) {
      await this.generateTodayNote().catch(
        (e) => new import_obsidian.Notice(`\u{1F4F0} fluxiaRSS \u751F\u6210\u4ECA\u65E5\u667A\u8BFB\u5931\u8D25\uFF1A${e.message}`)
      );
    }
  }
  // ---- 设置 ----
  async loadSettings() {
    var _a, _b;
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, (_a = data == null ? void 0 : data.settings) != null ? _a : {});
    this.ratings = (_b = data == null ? void 0 : data.ratings) != null ? _b : {};
  }
  async saveAll() {
    await this.saveData({ settings: this.settings, ratings: this.ratings });
  }
  // ---- 拉取与笔记 ----
  getTodayPath() {
    return `${this.settings.digestDir}/${todayStr()}.md`;
  }
  async todayExists() {
    return this.app.vault.adapter.exists(this.getTodayPath());
  }
  async fetchDigest() {
    const res = await fetchWithTimeout(
      {
        url: `${this.settings.apiBase}/api/v1/digest`,
        method: "GET"
      },
      1e4
    );
    if (res.status !== 200) throw new Error(`HTTP ${res.status}`);
    return res.json;
  }
  /**
   * 生成今日笔记。force=true 时覆盖重写（刷新）；否则已存在则跳过。
   * 返回文件（可能为 null：已存在且未强制刷新）。
   */
  async generateTodayNote(force = false) {
    const path = this.getTodayPath();
    if (!force && await this.app.vault.adapter.exists(path)) return null;
    const digest = await this.fetchDigest();
    digest.generated = (/* @__PURE__ */ new Date()).toISOString();
    const content = [
      "---",
      `date: ${digest.date}`,
      `generated: ${digest.generated}`,
      "---",
      "",
      `# \u{1F4F0} \u4ECA\u65E5\u667A\u8BFB \xB7 ${digest.date}`,
      "",
      `> \u751F\u6210\u4E8E ${new Date(digest.generated).toTimeString().slice(0, 5)} \xB7 \u5BF9\u6587\u7AE0\u6253\u5206/\u8DF3\u8FC7\uFF0C\u53CD\u9988\u8FDB\u5165\u957F\u671F\u8BB0\u5FC6\uFF0C\u5F71\u54CD\u660E\u5929\u6392\u5E8F\u3002`,
      "",
      "```fluxiars",
      JSON.stringify(digest),
      "```",
      ""
    ].join("\n");
    await this.app.vault.createFolder(this.settings.digestDir).catch(() => {
    });
    await this.app.vault.adapter.write(path, content);
    const f = this.app.vault.getAbstractFileByPath(path);
    return f instanceof import_obsidian.TFile ? f : null;
  }
  async openToday(refresh) {
    try {
      const file = await this.generateTodayNote(refresh);
      const target = file != null ? file : this.app.vault.getAbstractFileByPath(this.getTodayPath());
      if (target instanceof import_obsidian.TFile) {
        const leaf = this.app.workspace.getLeaf(false);
        await leaf.openFile(target);
      } else {
        new import_obsidian.Notice("\u4ECA\u65E5\u667A\u8BFB\u7B14\u8BB0\u4E0D\u5B58\u5728\uFF0C\u62C9\u53D6\u5931\u8D25");
      }
    } catch (e) {
      new import_obsidian.Notice(`\u{1F4F0} fluxiaRSS \u62C9\u53D6\u5931\u8D25\uFF1A${e.message}`);
    }
  }
  async maybeAutoRefresh() {
    const hour = (/* @__PURE__ */ new Date()).getHours();
    if (hour < this.settings.autoRefreshHour) return;
    if (await this.todayExists()) return;
    try {
      const file = await this.generateTodayNote();
      if (file) new import_obsidian.Notice("\u{1F4F0} \u4ECA\u65E5\u667A\u8BFB\u5DF2\u81EA\u52A8\u751F\u6210");
    } catch (e) {
      new import_obsidian.Notice(`\u{1F4F0} fluxiaRSS \u81EA\u52A8\u751F\u6210\u5931\u8D25\uFF1A${e.message}`);
    }
  }
  async collectAndRefresh() {
    var _a, _b;
    try {
      const res = await fetchWithTimeout(
        {
          url: `${this.settings.apiBase}/api/v1/collect`,
          method: "POST",
          contentType: "application/json",
          body: JSON.stringify({})
        },
        12e4
      );
      const body = res.json;
      new import_obsidian.Notice(`\u91C7\u96C6\u5B8C\u6210\uFF1A\u62C9\u53D6 ${(_a = body == null ? void 0 : body.fetched) != null ? _a : "?"}\uFF0C\u65B0\u589E ${(_b = body == null ? void 0 : body.new_added) != null ? _b : "?"}`);
    } catch (e) {
      new import_obsidian.Notice(`\u91C7\u96C6\u5931\u8D25\uFF1A${e.message}`);
    }
    await this.openToday(true);
  }
  // ---- 评分 ----
  async submitRating(articleId, score, action) {
    const res = await fetchWithTimeout(
      {
        url: `${this.settings.apiBase}/api/v1/rating`,
        method: "POST",
        contentType: "application/json",
        body: JSON.stringify({ article_id: articleId, score, action })
      },
      1e4
    );
    if (res.status !== 200 && res.status !== 201) {
      throw new Error(`HTTP ${res.status}`);
    }
    this.ratings[articleId] = { score, action };
    await this.saveAll();
  }
};
var DigestRenderer = class {
  constructor(plugin, digest) {
    this.plugin = plugin;
    this.digest = digest;
  }
  renderInto(el) {
    el.addClass("fluxiars-digest");
    el.empty();
    if (!this.digest.items || this.digest.items.length === 0) {
      el.createEl("p", {
        text: "\u4ECA\u65E5\u6682\u65E0\u5185\u5BB9\uFF08\u670D\u52A1\u7AEF\u51CC\u6668\u91C7\u96C6\u540E\u5237\u65B0\u5373\u53EF\uFF09\u3002"
      });
      return;
    }
    const header = el.createDiv({ cls: "fluxiars-header" });
    const gen = this.digest.generated ? new Date(this.digest.generated).toTimeString().slice(0, 5) : "\u2014";
    header.createEl("span", {
      text: `\u{1F4F0} ${this.digest.date} \xB7 ${this.digest.items.length} \u7BC7 \xB7 \u751F\u6210 ${gen}`
    });
    for (const item of this.digest.items) {
      this.renderItem(el, item);
    }
  }
  renderItem(el, item) {
    const card = el.createDiv({ cls: "fluxiars-card" });
    const top = card.createDiv({ cls: "fluxiars-card-top" });
    top.createEl("span", { cls: "fluxiars-rank", text: `${item.rank}` });
    top.createEl("a", { cls: "fluxiars-title", text: item.title, href: item.url }).addEventListener("click", (ev) => {
      ev.preventDefault();
      window.open(item.url, "_blank");
    });
    if (item.reason) {
      card.createEl("div", { cls: "fluxiars-reason", text: `\u6392\u5E8F\uFF1A${item.reason}` });
    }
    if (item.summary) {
      card.createEl("div", { cls: "fluxiars-summary", text: item.summary });
    }
    const row = card.createDiv({ cls: "fluxiars-actions" });
    this.renderActions(row, item);
  }
  renderActions(row, item) {
    const rated = this.plugin.ratings[item.article_id];
    if (rated) {
      const r = { score: rated.score, action: rated.action, label: "" };
      row.createEl("span", { cls: "fluxiars-rated", text: ratedText(r) });
      return;
    }
    for (const ra of RATED_ACTIONS) {
      const btn = row.createEl("button", { cls: "fluxiars-btn", text: ra.label });
      btn.addEventListener("click", async () => {
        btn.disabled = true;
        btn.setText("\u2026");
        try {
          await this.plugin.submitRating(item.article_id, ra.score, ra.action);
          row.empty();
          row.createEl("span", { cls: "fluxiars-rated", text: ratedText(ra) });
          new import_obsidian.Notice("\u5DF2\u8BB0\u5F55\u53CD\u9988 \u2714");
        } catch (e) {
          btn.disabled = false;
          btn.setText(ra.label);
          new import_obsidian.Notice(`\u8BC4\u5206\u5931\u8D25\uFF1A${e.message}`);
        }
      });
    }
  }
};
var FluxiaSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "fluxiaRSS \u4ECA\u65E5\u667A\u8BFB" });
    new import_obsidian.Setting(containerEl).setName("API \u5730\u5740").setDesc("fluxiaRSS \u670D\u52A1\u7AEF\u5730\u5740\uFF0C\u5982 http://192.168.1.5:8000").addText(
      (t) => t.setValue(this.plugin.settings.apiBase).onChange(async (v) => {
        this.plugin.settings.apiBase = v.trim() || DEFAULT_SETTINGS.apiBase;
        await this.plugin.saveAll();
      })
    );
    new import_obsidian.Setting(containerEl).setName("digest \u76EE\u5F55").setDesc("\u6BCF\u65E5\u7B14\u8BB0\u5B58\u653E\u76EE\u5F55\uFF08vault \u5185\u76F8\u5BF9\u8DEF\u5F84\uFF09").addText(
      (t) => t.setValue(this.plugin.settings.digestDir).onChange(async (v) => {
        this.plugin.settings.digestDir = v.trim() || DEFAULT_SETTINGS.digestDir;
        await this.plugin.saveAll();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u81EA\u52A8\u751F\u6210\u65F6\u95F4").setDesc("\u8FC7\u4E86\u8BE5\u5C0F\u65F6\u4E14\u4ECA\u65E5\u7B14\u8BB0\u4E0D\u5B58\u5728\u65F6\u81EA\u52A8\u751F\u6210\uFF080-23\uFF09").addSlider(
      (s) => s.setLimits(0, 23, 1).setValue(this.plugin.settings.autoRefreshHour).setDynamicTooltip().onChange(async (v) => {
        this.plugin.settings.autoRefreshHour = v;
        await this.plugin.saveAll();
      })
    );
  }
};
